### ISSUE TITLE
Add Retirement Trends Page

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/dash-apps#76]
Show retirement activity over time broken down by pool, as well as a detail listing of retirements

**Comment by jabby09** [comment]
Other requirements comments from discord...

- one more thing that we can display regarding retirements - klima retirements by carbon token over time breakdown chart
- yeah that would be nice, we have a ticket for a dedicated "Retirements" page that should include retirements by token over time, top retiring addresses broken down by token, etc
- We can focus on KlimaDAO retirement trends, at least initially
- If anything I’d want to compare with off chain retirement trends

**Comment by theprofessora** [comment]
for some reason this task doesn't have the "design in process" label, but this design is now in process (i'm working on it today)

**Comment by theprofessora** [comment]
v1 for review: https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO/Carbon-Dashboard?node-id=1941%3A1972

**Comment by 0xAurelius** [comment]
> v1 for review: https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO/Carbon-Dashboard?node-id=1941%3A1972

Overall looks good to me, the only thing is that the top-level "By XYZ" tab format hasn't been used before so need to make sure that's going to be practical to implement in Dash..

Worst case scenario we could do multiple "sub menu" items on the lefthand sidebar

**Comment by theprofessora** [comment]
Works for me! I can make a quick mock of what that looks like just in case

**Comment by theprofessora** [comment]
Design is done on this. LMK how to add that tag to this ticket

**Comment by jabby09** [comment]
Here is the link to the [shipped figma design](https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO/Carbon-Dashboard?node-id=2031%3A4142&t=xPyVuT8kee6xatCg-0)

**Comment by jabby09** [comment]
@0xAurelius would this be a good one for sekula?

**Comment by jabby09** [comment]
hey @milos1991 (sekula) I heard from @0xAurelius that you are assigned this bounty task.

Let me know if any of the design or requirements are not clear.

When you have had a chance to evaluate the scope of work, can you please let me know an estimated ETA for when you would be dev complete and ready for QA? thanks!

**Comment by jabby09** [comment]
@milos1991 checking in...how are you doing on this issue? Have you had a chance to estimate ETA for when you would be dev complete and ready for QA? thanks!

**Comment by milos1991** [comment]
Hey @jabby09  , sorry for not responding on github - didnt see an email, will fix that issue tho..

When it comes to the Retirement Trends task, Ive started working on it, and i plan to finish it by the end of this month, ideally by the 20th of February so we can iterate through design if needed.

By the way, there will be some changes compared to the current design - I've addressed that to @0xAurelius and he will mention them tomorrow on Product Meeting.

**Comment by jabby09** [comment]
Related PR's
https://github.com/KlimaDAO/dash-apps/pull/115
https://github.com/KlimaDAO/dash-apps/pull/116
https://github.com/KlimaDAO/dash-apps/pull/117

**Comment by jabby09** [comment]
> - Custom font style, this has not been included - current card design is the same as in the "Digital carbon supply page", do we want to have uniform card display regardless of a page?

@milos1991 
Yes we want uniform and consistent styles across all the pages.
The current prod version of the dashboard should be updated and correct.
This ticket (https://github.com/KlimaDAO/dash-apps/issues/87) was related to updating fonts/styles across all the pages and should have the css you need.
Does this help?

**Comment by jabby09** [comment]
> - Custom colors within the line chart on each page - colors that were picked are the default ones, do we want to have the exact colors as in the figma design?

@milos1991 
Yea good catch. I imagine the colours in the charts in figma are representative.
For now we should just try and be as consistent as we can between the different screens as in prod.
I did a scan on staging, this is the only chart I would change (screenshot), basically flip MC02 and NCT so the colours match the legend on this page https://carbon.klimadao.finance/carbon-pricing

![image](https://user-images.githubusercontent.com/103535195/221578671-cd6e1357-2a9e-46cf-9507-8bd953aed547.png)

**Comment by jabby09** [comment]
> - Table design - we are still using the default table design as on other dashboard pages; Proposed design is not feasible at this moment

I think for a first version of this page the same table design is fine.
What are the limitations on the leaderboard style design?

**Comment by milos1991** [comment]
Latest revision changes:
1. Applied font style according to this [guide](https://github.com/KlimaDAO/dash-apps/issues/87)
2. Added tooltip for Off-chain retirements:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15165767/221657946-b26a3eb4-6b54-4142-bdb9-33684e118dbf.png">
3. Swapped NCT and MCO2 colors on line chart:
<img width="105" alt="image" src="https://user-images.githubusercontent.com/15165767/221658144-958f8c00-e22b-4fd9-b5e4-3dd0e755d6f8.png">

**Comment by ShimonD-KlimaDAO** [comment]
### General 

1. When minimized, the new "Retirement Trends" tab is not showing. Also, "Digital Carbon Supply" has the wrong icon.
![image](https://user-images.githubusercontent.com/99001851/221711638-9787ad8c-4743-4a65-b6c6-0f63f9a150ad.png)
![image](https://user-images.githubusercontent.com/99001851/221711694-c9858888-37f5-4ed1-8eef-c4817b673465.png)


### By Pool

2. When a tco2 or c3t are directly retired without swapping from the pool, we see this under "Pool". Perhaps it should be labeled "Pool/Underlying", and we should fetch the tco2/c3t project name in this scenario, OR we should move those under "By Token". [Example transaction](https://polygonscan.com/tx/0x769bb8e461c8bfd76a3c4f644e08a0c181bf1957a442d6b8e3817172a23dd4ec) from when atmos and I were testing PR #937 in the frontend repo, which uses the v2 of the Retirement Aggregator.
![image](https://user-images.githubusercontent.com/99001851/221713229-b4698717-3d56-44a4-b9b0-8df63e178744.png)

Finally, are the above taken into account in the Retirement By Pool plot? If the data source is the same, they might be overlooked since they aren't labeled as a pool token.

3. I believe the Retirement By Pool plot should also have a tooltip, since the retirements are only the ones made through the RA.

### By Token

4. Similar to issue 2 above, the "By Token" data fails to label the retirement of individual tco2/c3t tokens correctly through the RA v2 bridge-specific retirement functions.
![image](https://user-images.githubusercontent.com/99001851/221715355-b8714b4a-9fc2-4890-9937-48d918a33448.png)

### By Chain

5. Unlike the previous two categories, the x-axis label (Date) isn't showing:
![image](https://user-images.githubusercontent.com/99001851/221716005-4336ec2c-86fa-42c3-b057-01f90a1f0728.png)


Final Notes
I believe that 2 and 3 are due to not taking account the Retirement Aggregator v2. We are already beginning to use it for certain features such as the PR I mentioned in 2, so it should be taken into account.
